apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: foyerdb
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        emptyDir: {}   # pour test local, pas persistant

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db   # ← ce nom doit matcher exactement le hostname dans ton application.properties
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306