apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
spec:
  selector:
    app: tpfoyer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort   # Donne un port haut (30000+) sur localhost